Background images
daohoangson/flutter_widget_from_html pull request #1057
Opened 2023-10-16 03:32 UTC by anttileppa

Adds basic support for using background images

2023-10-16 03:50 UTC, daohoangson commented
This is great!

I wanted to give you a quick heads-up that I'm currently in the process of getting v0.14 ready for release, and it's been quite a journey so far (take a look at #897). It might take a little while to review this PR and #1021. After we merge the new version, there might be some conflicts, but no worries! The underlying architecture is still quite similar, and I'm here to lend a hand in ironing out any kinks. Thank you for your contributions!

2023-10-26 08:32 UTC, daohoangson requested changes
Looking great. It just needs a conflict resolve with the `master` branch.

2023-10-26 08:32 UTC, daohoangson commented on packages/core/lib/src/core_widget_factory.dart
> +  DecorationImage? _buildDecorationImage(String? url) {
This method should be public, so the svg package can override it to support SVG background.

2023-10-26 08:32 UTC, daohoangson commented on packages/core/test/_.dart
> +      '[MemoryImage:size=${image.bytes.length}]';
Flutter's image providers have good `toString` already so maybe we don't need to do this?

2023-10-26 11:57 UTC, anttileppa commented
Merged master and resolved review comments

2023-10-27 00:04 UTC, merged

2023-10-27 00:04 UTC, daohoangson commented
Thank you for the resolve. I have merged this PR!