Selectable Text
daohoangson/flutter_widget_from_html pull request #438
Opened 2021-02-20 15:28 UTC by VB10

Hello dear
I need to select in text value so add selectable options core widget.

2021-02-21 12:01 UTC, daohoangson commented
What did you use to format the code? Please refrain from reformatting unrelated files from your PR. It's a bit hard to review at this state.

2021-02-22 16:18 UTC, VB10 commented
may formatter did not this, my vs code conifg  created this changes (number of line dart), i will fix that to send again

2021-02-22 16:21 UTC, daohoangson commented
That would be great. Thank you ❤️

2021-02-22 17:09 UTC, VB10 commented
i fixed formatting error thanks you everyting <3 @daohoangson

2021-02-27 10:01 UTC, dan-leech commented
I checked this on iOS but I cannot select a text.
How does it work? I've not found any example also.

I edited demo_app `hello_world_core.dart`, add isSelectableText: true but it seems it does nothing.

2021-02-27 10:43 UTC, VB10 commented
@dan-leech you right, I'll add an example at the demo folder

2021-02-27 15:18 UTC, VB10 commented
@dan-leech  you can look this image, just define selectableTrue and you did it.
![image](https://user-images.githubusercontent.com/17102578/109391420-05545e00-7928-11eb-90cc-cd471a79e3b7.png)

2021-02-27 15:19 UTC, daohoangson requested changes
I have cleaned up the PR to minimize the number of changes so it can be reviewed efficiently. At the current state, setting `isSelectableText: true` doesn't do anything. So maybe you need to double check the commits.

PS: It's unclear which IDE you are using but if it auto-formats again, you can execute `flutter format .` from the command line to reformat the files.

2021-02-27 15:19 UTC, daohoangson commented on packages/core/lib/src/core_widget_factory.dart
> +  Widget buildSelectableText(
This method is not being used anywhere.

2021-02-27 15:22 UTC, VB10 commented on packages/core/lib/src/core_widget_factory.dart
> +  Widget buildSelectableText(
this method called if you are Selectable not define.

2021-02-27 18:12 UTC, daohoangson commented
This doesn't seem to work with inline images? Or SUP/SUB tags?

2021-02-27 20:03 UTC, VB10 commented
yeah, this needs some improvement but the structure has more complexity, I'll develop well solution after to create pr again.

2021-02-27 20:04 UTC, closed without merging

2021-02-28 16:21 UTC, daohoangson commented
Understood. Let's keep poking this thing.